### ISSUE TITLE
feature: link to chrome://new-tab-page

### ISSUE THREAD

**Issue by MarcusUA** [lgarron/chrome-devices-in-new-tab#4]
Add a button/link to  chrome://new-tab-page  on top so there is convenient way to access chrome's default new tab page.

P.S. Love this extension. Solves so many problems. Only other wish is to have goups support, but even without that really happy with it.

**Comment by lgarron** [comment]
Hmm, this doesn't seem like an unreasonable idea, but I don't know if it makes sense to solve this at the individual extension level. Do you have a particular use case for this where it would be too annoying to disable and re-enable the extension?

**Comment by MarcusUA** [comment]
Opening any frequently used sites, like youtube, social media or work specific web sites, is very convenient from default new tab. 
Also, bookmarks are not shown with extension enabled.
I understand that some people might not use extension too often, but me personally use it multiple times on each browsing session, so I would find it very annoying to disable and re-enable it.

**Comment by lgarron** [comment]
I drafted a thorough comment here, but it seems to have gotten lost. :-(
Here goes again:

I don't plan to implement this because there are a few convenient alternatives[^1] and I don't think every new tab extension should work around this in its own way.

Some workarounds include:

- Setting a shortcut for `chrome://new-tab-page` using either the OS or a keyboard shortcut program (macOS settings, AutoHotkey, Keyboard Maestro, etc.). This could either navigate to the URL or open a bookmark from the menu.
- Using a separate Chrome extension to set a keyboard shortcut.
- Setting a custom search engine (at `chrome://settings/searchEngines`) with the URL `chrome://new-tab-page`. The omnibox is focused in a new tab by default, so a keyword like `n` (for "new tab page") allows you to press `n` followed by enter to get to the desired page, similar to a hardcoded autocomplete.
- Use the bookmarks bar or menu to click on a bookmark for `chrome://new-tab-page`. (Cmd/Ctrl-click to open in a new tab, although that opens in the background. Could possibly be worked around with a bookmarklet.)

I hope those alternatives help.

[^1]: Note that that these don't work on mobile, but that the extension can't be installed in mobile Chrome either.

**Comment by MarcusUA** [comment]
Hello,
Thanks for taking your time to respond. 
I would disagree with your decision, maybe suggest an option to enable/disable request button, but it looks like you have already made your mind on this. You are the creator and owner so its up to you anyway.

I guess I'll fork and try to customize it for myself.
